### ISSUE TITLE
Always outputs 404, not a single route works

### ISSUE THREAD

**Issue by Farhan5** [noahbuscher/Macaw#33]
Although I've proper configuration ( checked & reconfigured ),  it fails to route. It always prints '404' only. I found a older version of it may be, and checked that, it was working. Whats  the problem, how to fix it? And can we have a changelog? so that I can check which features I have in the older version and which Im missing..

**Comment by Farhan5** [comment]
It happens, even in root dir or other dirs..Any solution?

**Comment by rnarian** [comment]
Got the same problem. Could you figure it out @Farhan5?

**Comment by Zetberg** [comment]
@Farhan5 @rnarian rollback last commit to get it working again
https://github.com/noahbuscher/Macaw/commit/43bbc52eea261be45d9e482d4a3f7e0795991a73#diff-026ab8bc2553c00548f780b311a0915f

**Comment by leeoniya** [comment]
Sorry guys, that was my PR https://github.com/noahbuscher/Macaw/pull/32 that got merged.

As I mentioned in the PR, no unit tests exist in this repo, so I had no way of knowing if anything broke beyond my own basic testing. It may be worthwhile to create some tests so regressions like this don't happen. Also, the original issue that PR was solves would be broken again, so perhaps another solution that works for everyone is needed. :\

Feel free to revert the commit; I have migrated to my own router since. https://github.com/leeoniya/Route66.php

**Comment by black-snow** [comment]
Why is this still not fixed?

**Comment by noahbuscher** [comment]
Okay - sorry about that.

I am now working in Node, and have neglected to upkeep my PHP repo.

I rolled back the commit, and we should be good now. Thanks!

**Comment by black-snow** [comment]
@noahbuscher also the fixed version produced something link *"//some/path"* on some systems - had to `str_replace('//', '/', $uri)` to fix that

**Comment by black-snow** [comment]
(when app installed at doc root)
